### ISSUE TITLE
`Invalid literal value` error when using `deliver_later`

### ISSUE THREAD

**Issue by luizkowalski** [resend/resend-ruby#90]
Hey 👋🏻 

I have a mailer that lets me know when a user signed up:

```
def send_sign_up_email
  UserMailer.with(user: self).sign_up.deliver_later
end
```

when I use `deliver_later`, I get an error

`Error: Resend::Error::InvalidRequestError: Invalid literal value, expected ""`

```
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/resend-0.17.0/lib/resend/request.rb:51:in 'Resend::Request#handle_error!'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/resend-0.17.0/lib/resend/request.rb:43:in 'Resend::Request#perform'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/resend-0.17.0/lib/resend/emails.rb:13:in 'Resend::Emails.send'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/resend-0.17.0/lib/resend/mailer.rb:38:in 'Resend::Mailer#deliver!'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in 'Mail::Message#do_delivery'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/mail-2.8.1/lib/mail/message.rb:253:in 'block in Mail::Message#deliver'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/bundler/gems/rails-ea5db080a390/actionmailer/lib/action_mailer/base.rb:600:in 'block in ActionMailer::Base.deliver_mail'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/bundler/gems/rails-ea5db080a390/activesupport/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
/Users/luiz/.local/share/mise/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/bundler/gems/rails-ea5db080a390/activesupport/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
```

I thought it might have had something to do with passing the user object instead of the ID since it gets translated to GlobalID on the worker:

```
"UserMailer", "sign_up", "deliver_now", {"args" => [], "params" => {"user" => {"_aj_globalid" => "gid://switchboard/User/3"}, "_aj_symbol_keys" => ["user"]}, "_aj_ruby2_keywords" => ["params", "args"]}
```

but I also tried passing the user's ID like this: `UserMailer.with(user_id: id).sign_up.deliver_later` and got the same error.

worth note that `deliver_now!` works just fine

edit: noticed that using `deliver_later!` with a bang, works so its gotta be something with `perform_deliveries` and `raise_delivery_errors`

**Comment by drish** [comment]
hey @luizkowalski thanks for letting me know, im investigating it, im currently having  a bit of trouble reproducing it, would you mind sharing with me what your `sign_up` code looks like too ? 
Also whats your rails version ?

**Comment by luizkowalski** [comment]
sure, here it is everything I can think of:

```
class ApplicationMailer < ActionMailer::Base
  default from: "Switchboard <contact@switchboard.fun>"
  layout "mailer"
end

```

```
class UserMailer < ApplicationMailer
  def sign_up
    @user = params[:user]
    mail to: User::ADMIN_EMAIL, subject: "New user signed up!"
  end
end
```
I'm invoking with `UserMailer.with(user: self).sign_up.deliver_later`

I'm using Rails edge with Good Job as backend processor. My development configuration might be useful too

```
config.action_mailer.delivery_method = :resend

# Don't care if the mailer can't send.
config.action_mailer.raise_delivery_errors = true

config.action_mailer.perform_caching = false

config.action_mailer.default_url_options = { host: "localhost", port: 3000 }
```

**Comment by drish** [comment]
thanks a lot @luizkowalski, working on a fix

**Comment by ogirginc** [comment]
Hi @drish,

Unfortunately, we are still having this issue even after upgrading to the version `0.17.1`. 

Here is the Sentry trace: https://tasktag.sentry.io/share/issue/29fefe695de44cc98c577b5259b4a567

Is there any other info you would like me to share?

**Comment by drish** [comment]
thanks for reporting this @ogirginc, ill be investigating this today and will get back to you asap.

**Comment by ogirginc** [comment]
Thank you very much, Derich.

Please let me know if you need any data or any testing with a new version. I can update our staging and get back to you.

**Comment by drish** [comment]
@ogirginc thanks a lot for you patience, I have just [released v0.17.2](https://github.com/resend/resend-ruby/releases/tag/v0.17.2) which should fix that issue. Could you give it a try and let me know on the thread ?

**Comment by ogirginc** [comment]
Failed on v0.17.2: https://tasktag.sentry.io/share/issue/29fefe695de44cc98c577b5259b4a567/

**Comment by ogirginc** [comment]
Hi @drish. Apologies for not answering before. Somehow, I missed your notification.

At the moment, we are on `resend (0.20.0)`, and I can confirm the issue still persists.

I can share, but it's the regular Devise emails. I don't think we have anything in there that should cause an issue. That being said, here is the mailer code: 

```ruby
# frozen_string_literal: true

class DeviseMailer < Devise::Mailer
  include AbstractController::Callbacks

  include ::EmailHelper

  helper EmailHelper
  layout 'email'
  default from: 'TaskTag <info@tasktag.com>',
          queue: 'mailers'

  def confirmation_instructions(record, token, options = {})
    if options[:new_record].present?
      options[:template_name] = 'registration_email_confirmation'
      options[:subject] = 'Confirm your email address'
    else
      options[:template_name] = 'confirmation_instructions'
    end

    super
  end
end
```

```ruby
module EmailHelper
  STYLES = {
    h1: 'margin-bottom: 20px; margin-top: 10px; font-size: 32px;',
    h2: 'margin-top: 32px; font-size: 18px; font-weight: 500;',
    h3: 'margin-bottom: 10px; margin-top: 15px; font-size: 14px;',
    p: 'margin-bottom: 10px; line-height: 20px;',
    a: 'background-color: #18A87D; color: #fff; text-decoration: none; display: inline-block; border-radius: 8px; display: flex; padding: 12px 24px; justify-content: center; align-items: center; gap: 8px;' # rubocop:disable Layout/LineLength
  }.freeze

  def email_tag(type, options = {}, &)
    options[:style] ||= STYLES[type]
    options[:target] = '_blank' if type == :a
    content_tag(type, options, &)
  end
end
```

**Comment by drish** [comment]
thanks for letting me know @ogirginc, ill investigate this further with the core team.
